### ISSUE TITLE
How to run this module with no managed code / classic pipeline?

### ISSUE THREAD

**Issue by BenjaminAbt** [cloudflare/ModCloudFlareIIS#11]
How can I use this module with IIS Application pools running in "no managed code" / classic pipeline?

Two application which requires this:
* All new applications based in ASP.NET Core 1 and DNX
* Wordpress on IIS

**Comment by benjojo** [comment]
> All new applications based in ASP.NET Core 1 and DNX

I think you will need to rewrite the application logic to use the `CF-Connecting-IP` header.

> Wordpress on IIS

We have a plugin for WordPress that helps with correcting IP addresses: https://en-gb.wordpress.org/plugins/cloudflare/

**Comment by BenjaminAbt** [comment]
Okay, that works for me.
For the Core 1 thing I write my own library to provide that feature.
